site_name: Dinesh's Writings and Resume
site_url: https://dineshnair-doc.github.io/
use_directory_urls: false
theme:
  name: material
  features:
    - content.code.copy
nav:
  - Home: index.md
  - Resume: resumedineshnair.md
  - My Writings:
      - Python:
          - Getting Started with Python: mytechdocs/doc1/Getting_Started_with_Python.md
      - Flask:
          - Introduction to Flask: mytechdocs/doc2/techdoc2.md
site_dir: docs
docs_dir: src