site_name: Dinesh's Writings and Resume
site_url: https://dineshnair-doc.github.io/
use_directory_urls: false
theme:
  name: material
  features:
    - content.code.copy
markdown_extensions:
  - attr_list  # Enables adding attributes to Markdown elements
  - md_in_html # Enables Markdown inside HTML tags
copyright: Copyright &copy; 2024-2025 Dinesh Nair
nav:
  - Home: index.md
  - Resume: resumedineshnair.md
  - Tech Writing Portfolio:
      - Python:
          - Getting Started with Python: mytechdocs/doc1/Getting_Started_with_Python.md
          - Casting in Python: mytechdocs/doc2/Casting_in_Python.md
          - Lists, Dictionaries, Tuples, and Sets: mytechdocs/doc3/Python_Data_Structures.md
          - Classes and Objects: mytechdocs/doc4/Classes_and_Objects.md
      - Postman:
          - Introduction to Postman: mytechdocs/doc5/Postman_Intro.md
          - Obtaining Authorization: mytechdocs/doc6/Postman_Obtain_Auth.md
          - Sending Requests: mytechdocs/doc7/Sending_Requests.md
      - Flask:
          - Getting Started with Flask: mytechdocs/doc8/Flask_Intro.md
          - First REST API Using Flask: mytechdocs/doc9/First_REST_API_Flask.md
site_dir: docs
docs_dir: src