site_name: Dinesh's Writings and Resume
site_url: https://dineshnair-doc.github.io/
use_directory_urls: false
theme:
  name: material
  features:
    - content.code.copy
copyright: Copyright &copy; 2024-2025 Dinesh Nair
nav:
  - Home: index.md
  - Resume: resumedineshnair.md
  - My Writings:
      - Python:
          - Getting Started with Python: mytechdocs/doc1/Getting_Started_with_Python.md
          - Casting in Python: mytechdocs/doc2/Casting_in_Python.md
          - Lists, Dictionaries, Tuples, and Sets: mytechdocs/doc3/Python_Data_Structures.md
          - Classes and Objects: mytechdocs/doc4/Classes_and_Objects.md
      - Postman:
          - Introduction to Postman: mytechdocs/doc5/Postman_Intro.md
          - Obtaining Authorization: mytechdocs/doc6/Postman_Obtain_Auth.md
      - Flask:
          - Introduction to Flask: mytechdocs/doc22/techdoc2.md
site_dir: docs
docs_dir: src